### ISSUE TITLE
Update default role policy

### ISSUE THREAD

**Issue by MiloszFilimowski** [serverless-components/AwsLambda#46]
Can we also update the default policy as in the express repo?

This is based on: 
[serverless/components/issues/918](https://github.com/serverless/components/issues/918)
and:
[Update default role policy](https://github.com/serverless-components/express/pull/70)

I created a patch: https://github.com/MiloszFilimowski/aws-lambda/tree/patch-1

**Comment by MattiaPette** [comment]
Hi, there is already an open [PR](https://github.com/serverless-components/aws-lambda/pull/45) for this issue.
