### ISSUE TITLE
Is there a way to set `name` when using as a nested component?

### ISSUE THREAD

**Issue by EwanValentine** [serverless-components/AwsLambda#9]
Hey!

I'm using this component using `this.load`, and it's using the resourceId to generate the lambda name, it can't be overridden using inputs, I wondered if this was intentional, or if there's a specific way to update the name of a child component?

Specific line:
https://github.com/serverless-components/aws-lambda/blob/72a0c68371284df2ee86dfd199fd98c82e5cc185/serverless.js#L52

EDIT:
This seems to happen when using functions in the serverless.yml as well, I'm sure I'm probably doing something silly!

Cheers in advance!

**Comment by eahefnawy** [comment]
yeah it's intentional to keep resource names unique and avoid collision with existing resources. Do you have a strict use case for controlling the names of your resources? 😊

**Comment by EwanValentine** [comment]
Not especially, beyond finding them in the AWS console, that's all good. Thanks for the clarification!

**Comment by eahefnawy** [comment]
You may already know this by now, but you can always check the state files in the `.serverless` directory to know the outputs of all the components in the stack, which should include the lambda name.

**Comment by EwanValentine** [comment]
@eahefnawy awesome, yeah just had a look through those, that makes sense. Thanks again :)

**Comment by dhmacs** [comment]
@eahefnawy I need to invoke a lambda from another lambda, how should I implement this use case without knowing the lambda name?
